export const API = 'http://127.0.0.1:9000'

export const GET_NAVIGATION = 'GET_NAVIGATION'
export const ADD_NEW_NAVIGATION = 'ADD_NEW_NAVIGATION'
export const UPDATE_NAVIGATION = 'UPDATE_NAVIGATION'
export const DELETE_NAVIGATION = 'DELETE_NAVIGATION'

export const GET_CHARTS_SUCCESS = 'GET_CHARTS_SUCCESS'
export const ADD_NEW_CHART_SUCCESS = 'ADD_NEW_CHART_SUCCESS'
export const UPDATE_CHART_SUCCESS = 'UPDATE_CHART_SUCCESS'
export const DELETE_CHART_SUCCESS = 'DELETE_CHART_SUCCESS'

export const GET_GROUP = 'GET_GROUP'
export const ADD_NEW_GROUP = 'ADD_NEW_GROUP'
export const UPDATE_GROUP = 'UPDATE_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'

export const GET_PAGE = 'GET_PAGE'
export const ADD_NEW_PAGE = 'ADD_NEW_PAGE'
export const UPDATE_PAGE = 'UPDATE_PAGE'
export const DELETE_PAGE = 'DELETE_PAGE'

export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const HIDE_MESSAGE = 'HIDE_MESSAGE'
