export const GET_AUTH_CODE = 'GET_AUTH_CODE';
export const GET_AUTH_CODE_SUCCESS = 'GET_AUTH_CODE_SUCCESS';
export const GET_AUTH_CODE_FAILED = 'GET_AUTH_CODE_FAILED';

export const GET_ORG_NAME_LIST = 'GET_ORG_NAME_LIST';
export const GET_ORG_NAME_LIST_SUCCESS = 'GET_ORG_NAME_LIST_SUCCESS';
export const GET_ORG_NAME_LIST_FAILED = 'GET_ORG_NAME_LIST_FAILED';

export const GET_SUB_ORG_NAME_LIST = 'GET_SUB_ORG_NAME_LIST';
export const GET_SUB_ORG_NAME_LIST_SUCCESS = 'GET_SUB_ORG_NAME_LIST_SUCCESS';
export const GET_SUB_ORG_NAME_LIST_FAILED = 'GET_SUB_ORG_NAME_LIST_FAILED';

export const LOGOUT = 'LOGOUT';
