export const GET_GROUP_ONE = 'GET_GROUP_ONE';
export const GET_GROUP_ONE_SUCCESS = 'GET_GROUP_ONE_SUCCESS';
export const GET_GROUP_ONE_FAILED = 'GET_GROUP_ONE_FAILED';
export const GET_GROUP_TWO = 'GET_GROUP_TWO';
export const GET_GROUP_TWO_SUCCESS = 'GET_GROUP_TWO_SUCCESS';
export const GET_GROUP_TWO_FAILED = 'GET_GROUP_TWO_FAILED';